#
#	server.markhome.mcf.CFInt
#
#	Copyright (c) 2016-2026 Mark Stephen Sobkow
#	
#	Mark's Code Fractal 3.1 CFInt - Internet Essentials
#	
#	This file is part of Mark's Code Fractal CFInt.
#	
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#	
#	http://www.apache.org/licenses/LICENSE-2.0
#	
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#	
#
cfsec.javafx.Cluster.AttrPane.Id.EffLabel=Id
cfsec.javafx.Cluster.AttrPane.FullDomName.EffLabel=Full Domain Name
cfsec.javafx.Cluster.AttrPane.Description.EffLabel=Cluster Description
cfsec.javafx.Tenant.AttrPane.Id.EffLabel=Id
cfsec.javafx.Tenant.AttrPane.TenantName.EffLabel=TenantName
cfsec.javafx.Tenant.AttrPane.ContainerCluster.EffLabel=Cluster
cfsec.javafx.ISOCcy.AttrPane.ISOCcyId.EffLabel=ISOCcyId
cfsec.javafx.ISOCcy.AttrPane.ISOCode.EffLabel=ISOCode
cfsec.javafx.ISOCcy.AttrPane.Name.EffLabel=Name
cfsec.javafx.ISOCcy.AttrPane.UnitSymbol.EffLabel=UnitSymbol
cfsec.javafx.ISOCcy.AttrPane.Precis.EffLabel=Precis
cfsec.javafx.ISOCcy.AttrPane.ChildrenCtry.EffLabel=Ctry
cfsec.javafx.ISOCtry.AttrPane.ISOCtryId.EffLabel=ISOCtryId
cfsec.javafx.ISOCtry.AttrPane.ISOCode.EffLabel=ISOCode
cfsec.javafx.ISOCtry.AttrPane.Name.EffLabel=Name
cfsec.javafx.ISOCtryCcy.AttrPane.ContainerCtry.EffLabel=Ctry
cfsec.javafx.ISOCtryCcy.AttrPane.ParentCcy.EffLabel=Ccy
cfsec.javafx.ISOCtryLang.AttrPane.ContainerCtry.EffLabel=Ctry
cfsec.javafx.ISOCtryLang.AttrPane.ParentLang.EffLabel=Lang
cfsec.javafx.ISOLang.AttrPane.ISOLangId.EffLabel=ISOLangId
cfsec.javafx.ISOLang.AttrPane.ISO6392Code.EffLabel=ISO6392Code
cfsec.javafx.ISOLang.AttrPane.ISO6391Code.EffLabel=ISO6391Code
cfsec.javafx.ISOLang.AttrPane.EnglishName.EffLabel=EnglishName
cfsec.javafx.ISOLang.AttrPane.ChildrenCtry.EffLabel=Ctry
cfsec.javafx.ISOTZone.AttrPane.ISOTZoneId.EffLabel=ISO Timezone Id
cfsec.javafx.ISOTZone.AttrPane.Iso8601.EffLabel=ISO8601
cfsec.javafx.ISOTZone.AttrPane.TZName.EffLabel=Timezone Name
cfsec.javafx.ISOTZone.AttrPane.TZHourOffset.EffLabel=Timezone Hour Offset
cfsec.javafx.ISOTZone.AttrPane.TZMinOffset.EffLabel=Timezone Minute Offset
cfsec.javafx.ISOTZone.AttrPane.Description.EffLabel=Description
cfsec.javafx.ISOTZone.AttrPane.Visible.EffLabel=Visible
cfsec.javafx.SecUser.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecUser.AttrPane.LoginId.EffLabel=Login Id
cfsec.javafx.SecUser.AttrPane.DfltSysGrpName.EffLabel=Name
cfsec.javafx.SecUser.AttrPane.DfltClusGrpName.EffLabel=Name
cfsec.javafx.SecUser.AttrPane.DfltTentGrpName.EffLabel=Name
cfsec.javafx.SecUser.AttrPane.EMailAddress.EffLabel=EMail Address
cfsec.javafx.SecUser.AttrPane.EMailConfirmUuid6.EffLabel=EMail Confirm UUID6
cfsec.javafx.SecUser.AttrPane.PasswordHash.EffLabel=Password Hash
cfsec.javafx.SecUser.AttrPane.PasswordResetUuid6.EffLabel=Password Reset UUID6
cfsec.javafx.SecUser.AttrPane.ChildrenSysSecGrpMemb.EffLabel=System Security Group Members
cfsec.javafx.SecUserPassword.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecUserPassword.AttrPane.PWSetStamp.EffLabel=Password set at
cfsec.javafx.SecUserPassword.AttrPane.PasswordHash.EffLabel=Password Hash
cfsec.javafx.SecUserPWHistory.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecUserPWHistory.AttrPane.PWSetStamp.EffLabel=Password set at
cfsec.javafx.SecUserPWHistory.AttrPane.PWReplacedStamp.EffLabel=Password set at
cfsec.javafx.SecUserPWHistory.AttrPane.PasswordHash.EffLabel=Password Hash
cfsec.javafx.SecSysGrp.AttrPane.SecSysGrpId.EffLabel=System Security Group Id
cfsec.javafx.SecSysGrp.AttrPane.Name.EffLabel=Name
cfsec.javafx.SecSysGrp.AttrPane.SecLevel.EffLabel=Group Level
cfsec.javafx.SecSysGrp.AttrPane.ChildrenIncByGrp.EffLabel=Included by Group
cfsec.javafx.SecSysGrp.AttrPane.ChildrenMembByGrp.EffLabel=Members of Group
cfsec.javafx.SecSysGrpInc.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.SecSysGrpInc.AttrPane.ParentSubGroup.EffLabel=SubGroup
cfsec.javafx.SecSysGrpMemb.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.SecSysGrpMemb.AttrPane.ParentUser.EffLabel=User
cfsec.javafx.SecClusGrp.AttrPane.SecClusGrpId.EffLabel=Cluster Security Group Id
cfsec.javafx.SecClusGrp.AttrPane.Name.EffLabel=Name
cfsec.javafx.SecClusGrp.AttrPane.ChildrenIncByGrp.EffLabel=Included by Group
cfsec.javafx.SecClusGrp.AttrPane.ChildrenMembByGrp.EffLabel=Members of Group
cfsec.javafx.SecClusGrpInc.AttrPane.SecClusGrpId.EffLabel=Cluster Security Group Id
cfsec.javafx.SecClusGrpInc.AttrPane.InclName.EffLabel=Include Name
cfsec.javafx.SecClusGrpMemb.AttrPane.SecClusGrpId.EffLabel=Cluster Security Group Id
cfsec.javafx.SecClusGrpMemb.AttrPane.LoginId.EffLabel=Login Id
cfsec.javafx.SecTentGrp.AttrPane.SecTentGrpId.EffLabel=Tenant Security Group Id
cfsec.javafx.SecTentGrp.AttrPane.TenantId.EffLabel=Tenant Id
cfsec.javafx.SecTentGrp.AttrPane.Name.EffLabel=Name
cfsec.javafx.SecTentGrpInc.AttrPane.SecTentGrpId.EffLabel=Tenant Security Group Id
cfsec.javafx.SecTentGrpInc.AttrPane.InclName.EffLabel=Include Name
cfsec.javafx.SecTentGrpMemb.AttrPane.SecTentGrpId.EffLabel=Tenant Security Group Id
cfsec.javafx.SecTentGrpMemb.AttrPane.LoginId.EffLabel=Login Id
cfsec.javafx.SecSession.AttrPane.SecSessionId.EffLabel=Security Session Id
cfsec.javafx.SecSession.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecSession.AttrPane.Start.EffLabel=Start
cfsec.javafx.SecSession.AttrPane.Finish.EffLabel=Finish
cfsec.javafx.SecSession.AttrPane.SecProxyId.EffLabel=Security Proxy User Id
cfsec.javafx.SysCluster.AttrPane.SingletonId.EffLabel=Singleton
cfsec.javafx.SysCluster.AttrPane.ContainerCluster.EffLabel=Cluster
cfint.javafx.License.AttrPane.Id.EffLabel=Id
cfint.javafx.License.AttrPane.Name.EffLabel=Name
cfint.javafx.License.AttrPane.Description.EffLabel=Description
cfint.javafx.License.AttrPane.EmbeddedText.EffLabel=EmbeddedText
cfint.javafx.License.AttrPane.FullText.EffLabel=FullText
cfint.javafx.License.AttrPane.ContainerTopDomain.EffLabel=Top Domain
cfint.javafx.MajorVersion.AttrPane.Id.EffLabel=Id
cfint.javafx.MajorVersion.AttrPane.Name.EffLabel=Name
cfint.javafx.MajorVersion.AttrPane.Description.EffLabel=Description
cfint.javafx.MajorVersion.AttrPane.ContainerParentSPrj.EffLabel=Parent Sub Project
cfint.javafx.MimeType.AttrPane.MimeTypeId.EffLabel=MIME Type Id
cfint.javafx.MimeType.AttrPane.Name.EffLabel=Name
cfint.javafx.MimeType.AttrPane.FileTypes.EffLabel=FileTypes
cfint.javafx.MinorVersion.AttrPane.Id.EffLabel=Id
cfint.javafx.MinorVersion.AttrPane.Name.EffLabel=Name
cfint.javafx.MinorVersion.AttrPane.Description.EffLabel=Description
cfint.javafx.MinorVersion.AttrPane.ContainerParentMajVer.EffLabel=Parent Major Version
cfint.javafx.SubProject.AttrPane.Id.EffLabel=Id
cfint.javafx.SubProject.AttrPane.Name.EffLabel=Name
cfint.javafx.SubProject.AttrPane.Description.EffLabel=Description
cfint.javafx.SubProject.AttrPane.ContainerParentTPrj.EffLabel=Parent Top Project
cfint.javafx.Tld.AttrPane.Id.EffLabel=Id
cfint.javafx.Tld.AttrPane.Name.EffLabel=Name
cfint.javafx.Tld.AttrPane.Description.EffLabel=Description
cfint.javafx.Tld.AttrPane.ContainerTenant.EffLabel=Tenant
cfint.javafx.TopDomain.AttrPane.Id.EffLabel=Id
cfint.javafx.TopDomain.AttrPane.Name.EffLabel=Name
cfint.javafx.TopDomain.AttrPane.Description.EffLabel=Description
cfint.javafx.TopDomain.AttrPane.ContainerParentTld.EffLabel=Parent TLD
cfint.javafx.TopProject.AttrPane.Id.EffLabel=Id
cfint.javafx.TopProject.AttrPane.Name.EffLabel=Name
cfint.javafx.TopProject.AttrPane.Description.EffLabel=Description
cfint.javafx.TopProject.AttrPane.ContainerParentSDom.EffLabel=Parent Sub Domain
cfint.javafx.URLProtocol.AttrPane.URLProtocolId.EffLabel=URL Protocol Id
cfint.javafx.URLProtocol.AttrPane.Name.EffLabel=Name
cfint.javafx.URLProtocol.AttrPane.Description.EffLabel=Description
cfint.javafx.URLProtocol.AttrPane.IsSecure.EffLabel=IsSecure
